### ISSUE TITLE
with Visual studio 16.5 (last update)

### ISSUE THREAD

**Issue by Maleaume** [Fody/ModuleInit#140]
until kow  no problems.
With last visual studio update 16.5,  when run dotnet build command:

 `Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 47.63 ms for D:\source\IMPALA_Ecosystem\Impala\CodeCraft.ThreadsCommunication\CodeCraft.ThreadsCommunication.csproj.
  Restore completed in 47.62 ms for D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj.
  CodeCraft.ThreadsCommunication -> D:\source\IMPALA_Ecosystem\Impala\CodeCraft.ThreadsCommunication\bin\Debug\netstandard2.0\CodeCraft.ThreadsCommunication.dll
  Successfully created package 'D:\source\IMPALA_Ecosystem\Impala\CodeCraft.ThreadsCommunication\bin\Debug\CodeCraft.ThreadsCommunication.1.2.1.nupkg'.
MSBUILD : error : Fody: An unhandled exception occurred: [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : Exception: [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : Could not load file or assembly 'Mono.Cecil, Version=0.11.0.0, Culture=neutral, PublicKeyToken=1ca091877d12ca03'. The system cannot find the file specified. [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : Type: [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : System.IO.FileNotFoundException [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : StackTrace: [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error :    at InnerWeaver.Execute() [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error :    at Processor.ExecuteInOwnAssemblyLoadContext() in C:\projects\fody\Fody\Processor.cs:line 150 [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error :    at Processor.Inner() in C:\projects\fody\Fody\Processor.cs:line 122 [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error :    at Processor.Execute() in C:\projects\fody\Fody\Processor.cs:line 51 [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : Source: [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : FodyIsolated [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : TargetSite: [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error : Void Execute() [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]
MSBUILD : error :  [D:\source\IMPALA_Ecosystem\Impala\CodeCraft.Logger\CodeCraft.Logger.csproj]`

**Comment by SimonCropp** [comment]
To be raising issues [you should be a patron of Fody](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md#do-i-need-to-be-a-patron-to-raise-an-issue). Any issues raised by non Patrons may not be actively triaged, and eventually closed as stale.
