### ISSUE TITLE
Deprecate project?

### ISSUE THREAD

**Issue by distantcam** [Fody/ModuleInit#315]
So I just found out Module Initializers are in C#9.

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/module-initializers

Even if you're using an older target you can still manually include the attribute and the C#9 compiler will respect it.

https://sharplab.io/#v2:EYLgHgbALAPgdgQwLYFMDOAHBBjFACAAQEYA6AJQFc4AXAS1RIGEB7JDWgGxQCcBlHgG61caPAG8AsACg8svAG0AgtWrdawCtRQBVNAgDmKABTLV6zSgAqCboepoSAWRTUAFswAmAGjyKOHZgB3RwoOOgwuPABePAAzBA40FABKAF1pOUIAZjwkhJQPQgAmPEdPUJQASThaOgTaAC8eUzUNLTwQXxVWi3E8AF9pQalpAhziCGK8S3RqMo8K6traeqbucQy5eWJyKjoGFjZOHn5uIREncq4luo5GnnSZOTHCIkmCKFKrqprb++4jMkNk9ZMN+kA==

Is it time to deprecate this project?

**Comment by SimonCropp** [comment]
agreed. will do so this weekend

**Comment by SimonCropp** [comment]
done
