### ISSUE TITLE
Is there a way to dynamically locate dependencies with this?

### ISSUE THREAD

**Issue by georgiosd** [Fody/ModuleInit#5]
Hi!

I stumbled upon this and tried to use it to resolve some dependencies dynamically. Meaning, I set `CopyLocal = False` for them and added an `AssemblyResolve` handler that will load them from a known location. 

This seems to work if I do it manually from a console application as long as it is the first line of code. Doing it with `Fody.ModuleInit` on a PowerShell Module even when imported manually in LINQPad seems to fail with a `FileNotFoundException` of the dependency.

Any ideas how to make this work?

**Comment by SimonCropp** [comment]
i suspect those tools are doing some low level hyjacking of the assembly pipeline and hence trumping your code. perhaps send a sample the the linkpad and PS team and ask them

but in all honesty a library should not be responsible for where its dependencies are loaded from. that is the domain of the hosting application. so you should find another way to solve this problem

**Comment by georgiosd** [comment]
I traced the problem to having a type from the resolved dependency in on of the attributes that decorated the PS Cmdlet. And then forgot to update this! Sorry!

**Comment by SimonCropp** [comment]
Cool. Good to hear
