### ISSUE TITLE
ILRepack plugin please!

### ISSUE THREAD

**Issue by FixRM** [Fody/ModuleInit#7]
First of all, thank you so much for Costura plugin! It saves us tons of time spent on building, then comparing to ILMerge we uses previously. Unfortunately Richter-Egilsson approach can't be used in sandboxed environment as it uses AppDomain.AssemblyResolve event handler as it require full trust. As we have to deploy our dll's to Microsoft online services we have to build production assemblies separately.

Can you please create Costura-like plugin to pack assemblies using ILRepack with similar configuration options (include/exclude etc.) to be used in the same way? There are some similar projects like this: https://github.com/peters/ILRepack.MSBuild.Task, but it require build configuration. I believe Fody approach is much more convenient.

Thank you in advance!

**Comment by SimonCropp** [comment]
i think u raised this in the wrong repo
